### ISSUE TITLE
Approval

### ISSUE THREAD

**Issue by nerdyness** [ac3cloud/markdown-style-guide#1]
Channeling @gergnz with his standards council hat on!! :wink: 

NOTE: This is currently a public repo that needs to be duplicated to make it private.

[This](https://github.com/bulletproofnetworks/markdown-style-guide/blob/gh-pages/index.md) seems to be a reasonably well thought out style-guide. It came up in an issue previously about [$ signs in shell code](https://github.com/bulletproofnetworks/markdown-style-guide/blob/gh-pages/index.md#dollar-signs-in-shell-code) and I think while it's fairly extensive it could be worth adopting. I wouldn't reject PRs based on it but when in doubt we can refer to a style-guide.

**Comment by johnf** [comment]
Probably doesn't need to be made private. I'm hoping a markdown styleguide won't have any IP in it :smile:

**Comment by nerdyness** [comment]
Agreed. Though the public now knows that @gergnz owns a standards council hat... IP is a fine line :smile:

**Comment by gergnz** [comment]
Works for me.
